name: Call composite action

on: 
  workflow_dispatch:
    inputs:
      greeting:
        required: true
        description: Add your greeting
      name:
        required: true
        description: Please name the person to greet
  
jobs:
  Call_composite_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Call composite action
        id: callCompositeAction
        uses: ./.github/actions/demo-composite-actions
        with:
          greeting: ${{inputs.greeting}}
          name: ${{inputs.name}}
      - name: Print output from last step
        run: echo "${{steps.callCompositeAction.outputs.full-greeting}}"
