name: test me

on:
  # Webhook Event
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main
  issues:
    types:
      - opened
      - closed
  # Schedule Event
  schedule:
    - cron: 0 0 * * *
    - cron: 0 9 * * 0
  # Manual event
  workflow_dispatch:
    inputs:
      yourName:
        description: Whats your name man?
        required: true
        default: Zeeshan
      YouGood:
        description: You good man?
        required: true
        type: boolean
      WhatsUp:
        description: Whats uuuuuup
        required: false
        type: choice
        options:
          - Whats Uuuuuup
          - Not a lot
          - Meh

jobs:
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello World
  Job2:
    runs-on: ubuntu-latest
    needs: [Echo]
    steps:
      - name: Step2
        run: echo "${{ github.actor }} is now ruling the world."
      - name: Step3
        run: echo "Great!"
        if: ${{inputs.YouGood}}
      - name: Step4
        run: echo "You got this man"
        if: ${{inputs.YouGood == false}}
