# create a workflow with a name of your choice
# it should be triggered whenever there is a push on the main branch

# define 2 env variables: VAR1 and VAR2
# VAR1 is boolean
# VAR2 is text

# it should be triggered manually too
# it should have 2 jobs
# first job should contain 2 steps
# step 1: 
# - should be executed only if VAR1 is true
# - echo VAR2
# step 2:
# - echo your Name

# second job should execute only if job 1 is executed successfully
# job2 has only 1 step - do whatever you want
# commit the file and run the workflow, check if everything works

name: Test for day 2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      myVAR1:
        type: boolean
        required: true
      myVAR2:
        type: string
        required: true

env:
  VAR1: ${{inputs.myVAR1}}
  VAR2: ${{inputs.myVAR2}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: ${{env.VAR1}}
        run: echo $VAR2
      - name: step2
        run: echo ${{github.actor}}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: say good morning
        run:
          echo Good morning
